const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA'
const ADD_CARDS = 'ADD_CARDS'
const PLUS = 'PLUS'
const DELETE_CARDS_PRODUCT = 'DELETE_CARDS_PRODUCT'

export {
  GET_PRODUCTS_DATA,
  ADD_CARDS,
  PLUS,
  DELETE_CARDS_PRODUCT
}
